set(_AMENT_PACKAGE_NAME "tm5_gui")
set(tm5_gui_VERSION "0.0.0")
set(tm5_gui_MAINTAINER "kdl <kdl@todo.todo>")
set(tm5_gui_BUILD_DEPENDS "qtbase5-dev" "qt5-qmake" "rclcpp" "geometry_msgs" "sensor_msgs" "control_msgs" "nav_msgs" "std_srvs" "moveit_ros_planning_interface" "moveit_task_constructor_core" "tm5_bringup" "tm5_description" "tm5_moveit_config")
set(tm5_gui_BUILDTOOL_DEPENDS "ament_cmake")
set(tm5_gui_BUILD_EXPORT_DEPENDS "rclcpp" "geometry_msgs" "sensor_msgs" "control_msgs" "nav_msgs" "std_srvs" "moveit_ros_planning_interface" "moveit_task_constructor_core" "tm5_bringup" "tm5_description" "tm5_moveit_config")
set(tm5_gui_BUILDTOOL_EXPORT_DEPENDS )
set(tm5_gui_EXEC_DEPENDS "libqt5-core" "libqt5-core" "rclcpp" "geometry_msgs" "sensor_msgs" "control_msgs" "nav_msgs" "std_srvs" "moveit_ros_planning_interface" "moveit_task_constructor_core" "tm5_bringup" "tm5_description" "tm5_moveit_config")
set(tm5_gui_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(tm5_gui_GROUP_DEPENDS )
set(tm5_gui_MEMBER_OF_GROUPS )
set(tm5_gui_DEPRECATED "")
set(tm5_gui_EXPORT_TAGS)
list(APPEND tm5_gui_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
